### ISSUE TITLE
升级至Rails 3.2

### ISSUE THREAD

**Issue by ShiningRay** [qiushibaike/moumentei#9]
- [x] 移除所有的plugins
- [x] 将`find :conditions`替换成scope

**Comment by fiigii** [comment]
可以用Rails 3.2 运行吗？

**Comment by ShiningRay** [comment]
@fiigii 还在升级中，目前暂时还不行呢，估计过个两周能弄好吧

**Comment by ShiningRay** [comment]
@fiigii 我已经把代码升级到Rails3.2了
